#!/bin/bash

oIFS=$IFS

shopt -s expand_aliases

# make jshon read from /dev/null so it doesn't break 'read'
# by closing the file descriptor, and suppress errors
alias to_json='jshon -Q -F /dev/null -s'
#TODO alias read to read -r

IFS=$'\n'

echo '{'

# title
read -r line || echo "read error"
echo "$(to_json title): $(to_json $line),"

# description
read -r line || echo "read error"
echo "$(to_json description): $(to_json $line),"

read line   # gobble up blank line

echo "$(to_json comment): $(to_json 'generated by '$0),"

# sample text
echo "$(to_json text): ["

read -r line
echo -n "$(to_json $line)"

while read line; do
    if [ -z $line ]; then
        break
    else
        echo ","
        echo -n "$(to_json $line)"
    fi
done

echo
echo "],"

#read -r line   # gobble up blank line
#TODO why don't we need this?

# read regexes
echo "$(to_json regexes): ["

read -r line
echo -n "$(to_json $line)"

while read line; do
    if [ -z $line ]; then
        break
    else
        echo ","
        echo -n "$(to_json $line)"
    fi
done

echo
echo "]"

echo '}'

IFS=$oIFS
